#!/bin/bash
#
# (c) 2007 by Robert Manea
#
# Left mouse button toggles detailed view
# Right mouse button quits

#--[ Configuration ]---------------------------------------------------

# bg color
BG='#333333'
# fg color
FG='#a8a3f7'
# font
FNT='-*-*-*-*-*-*-12-*-*-*-*-*-iso8859'
# x position
XPOS=1140             #950
# y position
YPOS=0      #885
# title width
TWIDTH=125
# details area width
DWIDTH=150

# events & actions
ACT='button1=togglecollapse'


#----------------------------------------------------------------------

AWKS='/MemTotal/   {mtotal=$2};
/MemFree/    {mfree=$2};
/Active/     {mactive=$2};
/^Cached/     {mcached=$2};
/SwapTotal/  {swtotal=$2};
/SwapFree/   {swfree=$2};
END {
   print mtotal-mfree " " mtotal;
   print mactive " " mtotal;
   print mcached " " mtotal;
   print swtotal-swfree " " swtotal; }'

while echo ' ^tw()Mem:
Active:
Cached:
Swap  : ' | paste -d ' ' - <(awk "$AWKS" /proc/meminfo | gdbar -fg '#aecf96' -bg '#37383a' -w 50 -h 7); do
sleep 2
done | dzen2 -ta l -l 3 -fn $FNT -bg $BG -fg $FG -x $XPOS -y $YPOS -tw $TWIDTH -w $DWIDTH -sa c -e $ACT


