#!/bin/sh
#
#
#
# (c) 2007, by Jochen Schweizer
# with help from Robert Manea
 
FN='-*-terminus-bold-r-normal-*-12-*-*-*-*-*-*-*'
BG=black    #'#333333'
FG='#FFFFFF'
W=550
X=750
Y=0        #885
GH=6
GW=45
GFG='#a8a3f7'
GBG='#333'
 
CAPTION="^fg(dark orange)^i(/home/daniel/.xmonad/Icons/music.xbm)"
 
MAXPOS="100"
 
while true; do
  POS=`mpc | sed -ne 's/^.*(\([0-9]*\)%).*$/\1/p'`
  POSM="$POS $MAXPOS"
  echo -n "$CAPTION "
  echo "`mpc | sed -n '1p'`" | tr '\n' ' '
  echo "$POSM" | gdbar -h $GH -w $GW -fg $GFG -bg $GBG
  sleep 1 
done | dzen2 -p 60  -tw $W -x 920 -y 0 -fg $FG -bg $BG -fn $FN  -h 20 -ta l
