#!/bin/sh
#
# (c) 2007, by Robert Manea

# icons
ICONPATH=$HOME/.icons/xbm8x8
# network interface
INTERFACE=eth0
# update every x seconds
SLEEP=1
#colors
FG='#ccc'
BG='#222'
#geometry
WIDTH=210
X=850
Y=786

# Here we remember the previous rx/tx counts
RXB=`cat /sys/class/net/${INTERFACE}/statistics/rx_bytes`
TXB=`cat /sys/class/net/${INTERFACE}/statistics/tx_bytes`

while :; do

    # get new rx/tx counts
    RXBN=`cat /sys/class/net/${INTERFACE}/statistics/rx_bytes`
    TXBN=`cat /sys/class/net/${INTERFACE}/statistics/tx_bytes`

    # calculate the rates
    # format the values to 4 digit fields
    RXR=$(printf "%4d\n" $(echo "($RXBN - $RXB) / 1024/${SLEEP}" | bc))
    TXR=$(printf "%4d\n" $(echo "($TXBN - $TXB) / 1024/${SLEEP}" | bc))

    # print out the rates with some nice formatting
    echo "${INTERFACE}:^fg(white)${RXR} kB/s^fg($FG)^p(3)^i(${ICONPATH}/net_down_03.xbm)^fg(white)${TXR} kB/s^fg($FG)^p(3)^i(${ICONPATH}/net_up_03.xbm)^fg()"

    # reset old rates
    RXB=$RXBN; TXB=$TXBN

    sleep $SLEEP
done | dzen2 -x $X -y $Y  -tw $WIDTH -fg $FG -bg $BG -fn '-*-*-*-*-*-*-12-*-*-*-*-*-*'

